server:
  port: 8080

spring:
  application:
    name: bank-api
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

logging:
  level:
    com.example.bank: INFO # (INFO , WARN , ERROR)
    io.github.resilience4j : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true